// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string             `json:"id"`
	UserId                string             `json:"userId"`
	AccountId             string             `json:"accountId"`
	ProviderId            string             `json:"providerId"`
	AccessToken           *string            `json:"accessToken"`
	RefreshToken          *string            `json:"refreshToken"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refreshTokenExpiresAt"`
	Scope                 *string            `json:"scope"`
	IdToken               *string            `json:"idToken"`
	Password              *string            `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

type Event struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	EventDate   pgtype.Date        `json:"event_date"`
	Description *string            `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FloorPlan struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	Layout    []byte             `json:"layout"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Jwk struct {
	ID         string             `json:"id"`
	PublicKey  string             `json:"publicKey"`
	PrivateKey string             `json:"privateKey"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type Person struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Name        string             `json:"name"`
	GroupID     pgtype.UUID        `json:"group_id"`
	TableRef    *string            `json:"table_ref"`
	SeatRef     *string            `json:"seat_ref"`
	Parked      bool               `json:"parked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	BookedTable *string            `json:"booked_table"`
}

type Session struct {
	ID        string             `json:"id"`
	UserId    string             `json:"userId"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	IpAddress *string            `json:"ipAddress"`
	UserAgent *string            `json:"userAgent"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"emailVerified"`
	Image         *string            `json:"image"`
	Role          string             `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type Verification struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}
