// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSeat = `-- name: AssignSeat :one
UPDATE persons
SET table_ref = $2, seat_ref = $3, parked = FALSE, updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, name, group_id, table_ref, seat_ref, parked, created_at, updated_at, booked_table
`

type AssignSeatParams struct {
	ID       pgtype.UUID `json:"id"`
	TableRef *string     `json:"table_ref"`
	SeatRef  *string     `json:"seat_ref"`
}

func (q *Queries) AssignSeat(ctx context.Context, arg AssignSeatParams) (Person, error) {
	row := q.db.QueryRow(ctx, assignSeat, arg.ID, arg.TableRef, arg.SeatRef)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.GroupID,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const bulkParkPersons = `-- name: BulkParkPersons :exec
UPDATE persons
SET table_ref = NULL, seat_ref = NULL, parked = TRUE, updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

func (q *Queries) BulkParkPersons(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bulkParkPersons, dollar_1)
	return err
}

const countPersonsByEvent = `-- name: CountPersonsByEvent :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE NOT parked AND table_ref IS NOT NULL) AS seated,
    COUNT(*) FILTER (WHERE parked) AS parked_count
FROM persons
WHERE event_id = $1
`

type CountPersonsByEventRow struct {
	Total       int64 `json:"total"`
	Seated      int64 `json:"seated"`
	ParkedCount int64 `json:"parked_count"`
}

func (q *Queries) CountPersonsByEvent(ctx context.Context, eventID pgtype.UUID) (CountPersonsByEventRow, error) {
	row := q.db.QueryRow(ctx, countPersonsByEvent, eventID)
	var i CountPersonsByEventRow
	err := row.Scan(&i.Total, &i.Seated, &i.ParkedCount)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM "user"
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (name, event_date, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, event_date, description, created_by, created_at, updated_at
`

type CreateEventParams struct {
	Name        string      `json:"name"`
	EventDate   pgtype.Date `json:"event_date"`
	Description *string     `json:"description"`
	CreatedBy   string      `json:"created_by"`
}

// ============================================================
// Event queries
// ============================================================
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.EventDate,
		arg.Description,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFloorPlan = `-- name: CreateFloorPlan :one

INSERT INTO floor_plans (event_id) VALUES ($1) RETURNING id, event_id, layout, version, created_at, updated_at
`

// ============================================================
// Floor plan queries
// ============================================================
func (q *Queries) CreateFloorPlan(ctx context.Context, eventID pgtype.UUID) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, createFloorPlan, eventID)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (event_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, event_id, name, color, sort_order, created_at, updated_at
`

type CreateGroupParams struct {
	EventID pgtype.UUID `json:"event_id"`
	Name    string      `json:"name"`
	Color   string      `json:"color"`
}

// ============================================================
// Group queries
// ============================================================
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.EventID, arg.Name, arg.Color)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPerson = `-- name: CreatePerson :one

INSERT INTO persons (event_id, name, group_id, table_ref, seat_ref, parked, booked_table)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_id, name, group_id, table_ref, seat_ref, parked, created_at, updated_at, booked_table
`

type CreatePersonParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	Name        string      `json:"name"`
	GroupID     pgtype.UUID `json:"group_id"`
	TableRef    *string     `json:"table_ref"`
	SeatRef     *string     `json:"seat_ref"`
	Parked      bool        `json:"parked"`
	BookedTable *string     `json:"booked_table"`
}

// ============================================================
// Person queries
// ============================================================
func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.EventID,
		arg.Name,
		arg.GroupID,
		arg.TableRef,
		arg.SeatRef,
		arg.Parked,
		arg.BookedTable,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.GroupID,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM persons WHERE id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePerson, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user" WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, name, event_date, description, created_by, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFloorPlan = `-- name: GetFloorPlan :one
SELECT id, event_id, layout, version, created_at, updated_at FROM floor_plans WHERE event_id = $1
`

func (q *Queries) GetFloorPlan(ctx context.Context, eventID pgtype.UUID) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, getFloorPlan, eventID)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFloorPlanWithVersion = `-- name: GetFloorPlanWithVersion :one
SELECT id, event_id, layout, version, created_at, updated_at FROM floor_plans WHERE event_id = $1 AND version = $2
`

type GetFloorPlanWithVersionParams struct {
	EventID pgtype.UUID `json:"event_id"`
	Version int32       `json:"version"`
}

func (q *Queries) GetFloorPlanWithVersion(ctx context.Context, arg GetFloorPlanWithVersionParams) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, getFloorPlanWithVersion, arg.EventID, arg.Version)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, event_id, name, color, sort_order, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, event_id, name, group_id, table_ref, seat_ref, parked, created_at, updated_at, booked_table FROM persons WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.GroupID,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const getPersonBySeat = `-- name: GetPersonBySeat :one
SELECT id, event_id, name, group_id, table_ref, seat_ref, parked, created_at, updated_at, booked_table FROM persons
WHERE event_id = $1 AND table_ref = $2 AND seat_ref = $3 AND NOT parked
LIMIT 1
`

type GetPersonBySeatParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	TableRef *string     `json:"table_ref"`
	SeatRef  *string     `json:"seat_ref"`
}

func (q *Queries) GetPersonBySeat(ctx context.Context, arg GetPersonBySeatParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonBySeat, arg.EventID, arg.TableRef, arg.SeatRef)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.GroupID,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, "emailVerified", image, role, "createdAt", "updatedAt"
FROM "user"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, name, email, "emailVerified", image, role, "createdAt", "updatedAt"
FROM "user"
WHERE id = $1
`

// ============================================================
// User queries (BetterAuth user table)
// ============================================================
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, event_date, description, created_by, created_at, updated_at FROM events ORDER BY event_date DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByEvent = `-- name: ListGroupsByEvent :many
SELECT id, event_id, name, color, sort_order, created_at, updated_at FROM groups WHERE event_id = $1 ORDER BY sort_order, name
`

func (q *Queries) ListGroupsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParkedPersons = `-- name: ListParkedPersons :many
SELECT p.id, p.event_id, p.name, p.group_id, p.table_ref, p.seat_ref, p.parked, p.created_at, p.updated_at, p.booked_table, g.name AS group_name, g.color AS group_color
FROM persons p
LEFT JOIN groups g ON g.id = p.group_id
WHERE p.event_id = $1 AND p.parked = TRUE
ORDER BY p.name
`

type ListParkedPersonsRow struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Name        string             `json:"name"`
	GroupID     pgtype.UUID        `json:"group_id"`
	TableRef    *string            `json:"table_ref"`
	SeatRef     *string            `json:"seat_ref"`
	Parked      bool               `json:"parked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	BookedTable *string            `json:"booked_table"`
	GroupName   *string            `json:"group_name"`
	GroupColor  *string            `json:"group_color"`
}

func (q *Queries) ListParkedPersons(ctx context.Context, eventID pgtype.UUID) ([]ListParkedPersonsRow, error) {
	rows, err := q.db.Query(ctx, listParkedPersons, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParkedPersonsRow{}
	for rows.Next() {
		var i ListParkedPersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.GroupID,
			&i.TableRef,
			&i.SeatRef,
			&i.Parked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookedTable,
			&i.GroupName,
			&i.GroupColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsByEvent = `-- name: ListPersonsByEvent :many
SELECT p.id, p.event_id, p.name, p.group_id, p.table_ref, p.seat_ref, p.parked, p.created_at, p.updated_at, p.booked_table, g.name AS group_name, g.color AS group_color
FROM persons p
LEFT JOIN groups g ON g.id = p.group_id
WHERE p.event_id = $1
ORDER BY p.name
`

type ListPersonsByEventRow struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Name        string             `json:"name"`
	GroupID     pgtype.UUID        `json:"group_id"`
	TableRef    *string            `json:"table_ref"`
	SeatRef     *string            `json:"seat_ref"`
	Parked      bool               `json:"parked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	BookedTable *string            `json:"booked_table"`
	GroupName   *string            `json:"group_name"`
	GroupColor  *string            `json:"group_color"`
}

func (q *Queries) ListPersonsByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListPersonsByEventRow, error) {
	rows, err := q.db.Query(ctx, listPersonsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonsByEventRow{}
	for rows.Next() {
		var i ListPersonsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.GroupID,
			&i.TableRef,
			&i.SeatRef,
			&i.Parked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookedTable,
			&i.GroupName,
			&i.GroupColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsByGroup = `-- name: ListPersonsByGroup :many
SELECT p.id, p.event_id, p.name, p.group_id, p.table_ref, p.seat_ref, p.parked, p.created_at, p.updated_at, p.booked_table, g.name AS group_name, g.color AS group_color
FROM persons p
LEFT JOIN groups g ON g.id = p.group_id
WHERE p.group_id = $1
ORDER BY p.name
`

type ListPersonsByGroupRow struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Name        string             `json:"name"`
	GroupID     pgtype.UUID        `json:"group_id"`
	TableRef    *string            `json:"table_ref"`
	SeatRef     *string            `json:"seat_ref"`
	Parked      bool               `json:"parked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	BookedTable *string            `json:"booked_table"`
	GroupName   *string            `json:"group_name"`
	GroupColor  *string            `json:"group_color"`
}

func (q *Queries) ListPersonsByGroup(ctx context.Context, groupID pgtype.UUID) ([]ListPersonsByGroupRow, error) {
	rows, err := q.db.Query(ctx, listPersonsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonsByGroupRow{}
	for rows.Next() {
		var i ListPersonsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.GroupID,
			&i.TableRef,
			&i.SeatRef,
			&i.Parked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookedTable,
			&i.GroupName,
			&i.GroupColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsByTable = `-- name: ListPersonsByTable :many
SELECT p.id, p.event_id, p.name, p.group_id, p.table_ref, p.seat_ref, p.parked, p.created_at, p.updated_at, p.booked_table, g.name AS group_name, g.color AS group_color
FROM persons p
LEFT JOIN groups g ON g.id = p.group_id
WHERE p.event_id = $1 AND p.table_ref = $2 AND NOT p.parked
ORDER BY p.seat_ref
`

type ListPersonsByTableParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	TableRef *string     `json:"table_ref"`
}

type ListPersonsByTableRow struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Name        string             `json:"name"`
	GroupID     pgtype.UUID        `json:"group_id"`
	TableRef    *string            `json:"table_ref"`
	SeatRef     *string            `json:"seat_ref"`
	Parked      bool               `json:"parked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	BookedTable *string            `json:"booked_table"`
	GroupName   *string            `json:"group_name"`
	GroupColor  *string            `json:"group_color"`
}

func (q *Queries) ListPersonsByTable(ctx context.Context, arg ListPersonsByTableParams) ([]ListPersonsByTableRow, error) {
	rows, err := q.db.Query(ctx, listPersonsByTable, arg.EventID, arg.TableRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonsByTableRow{}
	for rows.Next() {
		var i ListPersonsByTableRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.GroupID,
			&i.TableRef,
			&i.SeatRef,
			&i.Parked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookedTable,
			&i.GroupName,
			&i.GroupColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, "emailVerified", image, role, "createdAt", "updatedAt"
FROM "user"
ORDER BY "createdAt" DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Image,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeGroups = `-- name: MergeGroups :exec
UPDATE persons SET group_id = $2, updated_at = NOW() WHERE group_id = $1
`

type MergeGroupsParams struct {
	GroupID   pgtype.UUID `json:"group_id"`
	GroupID_2 pgtype.UUID `json:"group_id_2"`
}

func (q *Queries) MergeGroups(ctx context.Context, arg MergeGroupsParams) error {
	_, err := q.db.Exec(ctx, mergeGroups, arg.GroupID, arg.GroupID_2)
	return err
}

const parkPerson = `-- name: ParkPerson :one
UPDATE persons
SET table_ref = NULL, seat_ref = NULL, parked = TRUE, updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, name, group_id, table_ref, seat_ref, parked, created_at, updated_at, booked_table
`

func (q *Queries) ParkPerson(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, parkPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.GroupID,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const swapSeats = `-- name: SwapSeats :exec
WITH person_a AS (
    SELECT table_ref, seat_ref FROM persons WHERE persons.id = $1
), person_b AS (
    SELECT table_ref, seat_ref FROM persons WHERE persons.id = $2
)
UPDATE persons SET
    table_ref = CASE
        WHEN persons.id = $1 THEN (SELECT table_ref FROM person_b)
        WHEN persons.id = $2 THEN (SELECT table_ref FROM person_a)
    END,
    seat_ref = CASE
        WHEN persons.id = $1 THEN (SELECT seat_ref FROM person_b)
        WHEN persons.id = $2 THEN (SELECT seat_ref FROM person_a)
    END,
    updated_at = NOW()
WHERE persons.id IN ($1, $2)
`

type SwapSeatsParams struct {
	ID   pgtype.UUID `json:"id"`
	ID_2 pgtype.UUID `json:"id_2"`
}

func (q *Queries) SwapSeats(ctx context.Context, arg SwapSeatsParams) error {
	_, err := q.db.Exec(ctx, swapSeats, arg.ID, arg.ID_2)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $2, event_date = $3, description = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, event_date, description, created_by, created_at, updated_at
`

type UpdateEventParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	EventDate   pgtype.Date `json:"event_date"`
	Description *string     `json:"description"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.EventDate,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFloorPlanLayout = `-- name: UpdateFloorPlanLayout :one
UPDATE floor_plans
SET layout = $2, version = version + 1, updated_at = NOW()
WHERE event_id = $1
RETURNING id, event_id, layout, version, created_at, updated_at
`

type UpdateFloorPlanLayoutParams struct {
	EventID pgtype.UUID `json:"event_id"`
	Layout  []byte      `json:"layout"`
}

func (q *Queries) UpdateFloorPlanLayout(ctx context.Context, arg UpdateFloorPlanLayoutParams) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, updateFloorPlanLayout, arg.EventID, arg.Layout)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = $2, color = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, name, color, sort_order, created_at, updated_at
`

type UpdateGroupParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Color string      `json:"color"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name, arg.Color)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET name = $2, group_id = $3, booked_table = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, name, group_id, table_ref, seat_ref, parked, created_at, updated_at, booked_table
`

type UpdatePersonParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	GroupID     pgtype.UUID `json:"group_id"`
	BookedTable *string     `json:"booked_table"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.ID,
		arg.Name,
		arg.GroupID,
		arg.BookedTable,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.GroupID,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE "user" SET role = $2, "updatedAt" = NOW() WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
