// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSeat = `-- name: AssignSeat :one
UPDATE persons
SET table_ref = $2, seat_ref = $3, parked = FALSE, updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, name, table_ref, seat_ref, parked, created_at, updated_at, booked_table
`

type AssignSeatParams struct {
	ID       pgtype.UUID `json:"id"`
	TableRef *string     `json:"table_ref"`
	SeatRef  *string     `json:"seat_ref"`
}

func (q *Queries) AssignSeat(ctx context.Context, arg AssignSeatParams) (Person, error) {
	row := q.db.QueryRow(ctx, assignSeat, arg.ID, arg.TableRef, arg.SeatRef)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const bulkParkPersons = `-- name: BulkParkPersons :exec
UPDATE persons
SET table_ref = NULL, seat_ref = NULL, parked = TRUE, updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

func (q *Queries) BulkParkPersons(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bulkParkPersons, dollar_1)
	return err
}

const countPersonsByEvent = `-- name: CountPersonsByEvent :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE NOT parked AND table_ref IS NOT NULL) AS seated,
    COUNT(*) FILTER (WHERE parked) AS parked_count
FROM persons
WHERE event_id = $1
`

type CountPersonsByEventRow struct {
	Total       int64 `json:"total"`
	Seated      int64 `json:"seated"`
	ParkedCount int64 `json:"parked_count"`
}

func (q *Queries) CountPersonsByEvent(ctx context.Context, eventID pgtype.UUID) (CountPersonsByEventRow, error) {
	row := q.db.QueryRow(ctx, countPersonsByEvent, eventID)
	var i CountPersonsByEventRow
	err := row.Scan(&i.Total, &i.Seated, &i.ParkedCount)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM "user"
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (name, event_date, description, created_by, organization_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, event_date, description, created_by, created_at, updated_at, organization_id
`

type CreateEventParams struct {
	Name           string      `json:"name"`
	EventDate      pgtype.Date `json:"event_date"`
	Description    *string     `json:"description"`
	CreatedBy      string      `json:"created_by"`
	OrganizationID *string     `json:"organization_id"`
}

// ============================================================
// Event queries
// ============================================================
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.EventDate,
		arg.Description,
		arg.CreatedBy,
		arg.OrganizationID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const createFloorPlan = `-- name: CreateFloorPlan :one

INSERT INTO floor_plans (event_id) VALUES ($1) RETURNING id, event_id, layout, version, created_at, updated_at
`

// ============================================================
// Floor plan queries
// ============================================================
func (q *Queries) CreateFloorPlan(ctx context.Context, eventID pgtype.UUID) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, createFloorPlan, eventID)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPerson = `-- name: CreatePerson :one

INSERT INTO persons (event_id, name, table_ref, seat_ref, parked, booked_table)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, name, table_ref, seat_ref, parked, created_at, updated_at, booked_table
`

type CreatePersonParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	Name        string      `json:"name"`
	TableRef    *string     `json:"table_ref"`
	SeatRef     *string     `json:"seat_ref"`
	Parked      bool        `json:"parked"`
	BookedTable *string     `json:"booked_table"`
}

// ============================================================
// Person queries
// ============================================================
func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.EventID,
		arg.Name,
		arg.TableRef,
		arg.SeatRef,
		arg.Parked,
		arg.BookedTable,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM persons WHERE id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePerson, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user" WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, name, event_date, description, created_by, created_at, updated_at, organization_id FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getFloorPlan = `-- name: GetFloorPlan :one
SELECT id, event_id, layout, version, created_at, updated_at FROM floor_plans WHERE event_id = $1
`

func (q *Queries) GetFloorPlan(ctx context.Context, eventID pgtype.UUID) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, getFloorPlan, eventID)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFloorPlanWithVersion = `-- name: GetFloorPlanWithVersion :one
SELECT id, event_id, layout, version, created_at, updated_at FROM floor_plans WHERE event_id = $1 AND version = $2
`

type GetFloorPlanWithVersionParams struct {
	EventID pgtype.UUID `json:"event_id"`
	Version int32       `json:"version"`
}

func (q *Queries) GetFloorPlanWithVersion(ctx context.Context, arg GetFloorPlanWithVersionParams) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, getFloorPlanWithVersion, arg.EventID, arg.Version)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one

SELECT role FROM member WHERE "organizationId" = $1 AND "userId" = $2
`

type GetMemberRoleParams struct {
	OrganizationId string `json:"organizationId"`
	UserId         string `json:"userId"`
}

// ============================================================
// Organization queries
// ============================================================
func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.OrganizationId, arg.UserId)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, event_id, name, table_ref, seat_ref, parked, created_at, updated_at, booked_table FROM persons WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const getPersonBySeat = `-- name: GetPersonBySeat :one
SELECT id, event_id, name, table_ref, seat_ref, parked, created_at, updated_at, booked_table FROM persons
WHERE event_id = $1 AND table_ref = $2 AND seat_ref = $3 AND NOT parked
LIMIT 1
`

type GetPersonBySeatParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	TableRef *string     `json:"table_ref"`
	SeatRef  *string     `json:"seat_ref"`
}

func (q *Queries) GetPersonBySeat(ctx context.Context, arg GetPersonBySeatParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonBySeat, arg.EventID, arg.TableRef, arg.SeatRef)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, "emailVerified", image, role, "createdAt", "updatedAt"
FROM "user"
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"emailVerified"`
	Image         *string            `json:"image"`
	Role          string             `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, name, email, "emailVerified", image, role, "createdAt", "updatedAt"
FROM "user"
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"emailVerified"`
	Image         *string            `json:"image"`
	Role          string             `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

// ============================================================
// User queries (BetterAuth user table)
// ============================================================
func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, event_date, description, created_by, created_at, updated_at, organization_id FROM events ORDER BY event_date DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByOrganization = `-- name: ListEventsByOrganization :many
SELECT id, name, event_date, description, created_by, created_at, updated_at, organization_id FROM events WHERE organization_id = $1 ORDER BY event_date DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListEventsByOrganization(ctx context.Context, organizationID *string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByUser = `-- name: ListEventsByUser :many
SELECT id, name, event_date, description, created_by, created_at, updated_at, organization_id FROM events WHERE created_by = $1 ORDER BY event_date DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListEventsByUser(ctx context.Context, createdBy string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParkedPersons = `-- name: ListParkedPersons :many
SELECT id, event_id, name, table_ref, seat_ref, parked, created_at, updated_at, booked_table FROM persons
WHERE event_id = $1 AND parked = TRUE
ORDER BY name
`

func (q *Queries) ListParkedPersons(ctx context.Context, eventID pgtype.UUID) ([]Person, error) {
	rows, err := q.db.Query(ctx, listParkedPersons, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.TableRef,
			&i.SeatRef,
			&i.Parked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookedTable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsByEvent = `-- name: ListPersonsByEvent :many
SELECT id, event_id, name, table_ref, seat_ref, parked, created_at, updated_at, booked_table FROM persons WHERE event_id = $1 ORDER BY name
`

func (q *Queries) ListPersonsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPersonsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.TableRef,
			&i.SeatRef,
			&i.Parked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookedTable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsByTable = `-- name: ListPersonsByTable :many
SELECT id, event_id, name, table_ref, seat_ref, parked, created_at, updated_at, booked_table FROM persons
WHERE event_id = $1 AND table_ref = $2 AND NOT parked
ORDER BY seat_ref
`

type ListPersonsByTableParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	TableRef *string     `json:"table_ref"`
}

func (q *Queries) ListPersonsByTable(ctx context.Context, arg ListPersonsByTableParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPersonsByTable, arg.EventID, arg.TableRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.TableRef,
			&i.SeatRef,
			&i.Parked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookedTable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, "emailVerified", image, role, "createdAt", "updatedAt"
FROM "user"
ORDER BY "createdAt" DESC
`

type ListUsersRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"emailVerified"`
	Image         *string            `json:"image"`
	Role          string             `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Image,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const parkPerson = `-- name: ParkPerson :one
UPDATE persons
SET table_ref = NULL, seat_ref = NULL, parked = TRUE, updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, name, table_ref, seat_ref, parked, created_at, updated_at, booked_table
`

func (q *Queries) ParkPerson(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, parkPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const swapSeats = `-- name: SwapSeats :exec
WITH person_a AS (
    SELECT table_ref, seat_ref FROM persons WHERE persons.id = $1
), person_b AS (
    SELECT table_ref, seat_ref FROM persons WHERE persons.id = $2
)
UPDATE persons SET
    table_ref = CASE
        WHEN persons.id = $1 THEN (SELECT table_ref FROM person_b)
        WHEN persons.id = $2 THEN (SELECT table_ref FROM person_a)
    END,
    seat_ref = CASE
        WHEN persons.id = $1 THEN (SELECT seat_ref FROM person_b)
        WHEN persons.id = $2 THEN (SELECT seat_ref FROM person_a)
    END,
    updated_at = NOW()
WHERE persons.id IN ($1, $2)
`

type SwapSeatsParams struct {
	ID   pgtype.UUID `json:"id"`
	ID_2 pgtype.UUID `json:"id_2"`
}

func (q *Queries) SwapSeats(ctx context.Context, arg SwapSeatsParams) error {
	_, err := q.db.Exec(ctx, swapSeats, arg.ID, arg.ID_2)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $2, event_date = $3, description = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, event_date, description, created_by, created_at, updated_at, organization_id
`

type UpdateEventParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	EventDate   pgtype.Date `json:"event_date"`
	Description *string     `json:"description"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.EventDate,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const updateFloorPlanLayout = `-- name: UpdateFloorPlanLayout :one
UPDATE floor_plans
SET layout = $2, version = version + 1, updated_at = NOW()
WHERE event_id = $1
RETURNING id, event_id, layout, version, created_at, updated_at
`

type UpdateFloorPlanLayoutParams struct {
	EventID pgtype.UUID `json:"event_id"`
	Layout  []byte      `json:"layout"`
}

func (q *Queries) UpdateFloorPlanLayout(ctx context.Context, arg UpdateFloorPlanLayoutParams) (FloorPlan, error) {
	row := q.db.QueryRow(ctx, updateFloorPlanLayout, arg.EventID, arg.Layout)
	var i FloorPlan
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Layout,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET name = $2, booked_table = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, name, table_ref, seat_ref, parked, created_at, updated_at, booked_table
`

type UpdatePersonParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	BookedTable *string     `json:"booked_table"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson, arg.ID, arg.Name, arg.BookedTable)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.TableRef,
		&i.SeatRef,
		&i.Parked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookedTable,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE "user" SET role = $2, "updatedAt" = NOW() WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
